# Generated by Django 3.1.1 on 2020-09-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_jasoseol_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jasoseol',
            name='author',
        ),
    ]
